export const MUNICIPIO_MACROZONA_HIERARCHY = {
  Medellín: [
    "Aranjuez",
    "Belén",
    "Buenos Aires",
    "Castilla",
    "Corregimiento Altavista",
    "Corregimiento San Antonio",
    "Corregimiento San Cristóbal",
    "Corregimiento San Sebastián",
    "Corregimiento Santa Elena",
    "Doce de Octubre",
    "El Poblado",
    "Guayabal",
    "La América",
    "La Candelaria",
    "Laureles-Estadio",
    "Manrique",
    "Popular",
    "Robledo",
    "San Javier",
    "Santa Cruz",
    "Villa Hermosa",
  ],
  Barbosa: ["Rural Barbosa", "Urbana Barbosa"],
  Bello: [
    "Acevedo",
    "Altos de Niquía",
    "Bellavista",
    "Centro Bello",
    "Croacia El Pinar",
    "Fontidueño",
    "Guasimalito",
    "La Cumbre - El Carmelo",
    "Madera",
    "Niquía",
    "Paris",
    "Rural",
    "Santa Ana",
  ],
  Caldas: ["Rural Caldas", "Urbana Caldas"],
  Copacabana: ["Rural Copacabana", "Urbana Copacabana"],
  Envigado: [
    "Alcalá",
    "El Dorado - La Paz",
    "El Esmeraldal",
    "La Inmaculada",
    "Las Flores - Alto de Misael",
    "Las Vegas",
    "San José",
    "San Marcos",
    "Vereda El Escobero",
    "Vereda El Vallano",
    "Vereda Las Palmas",
    "Vereda Perico y Pantanillo",
    "Z. Centro",
  ],
  Girardota: ["Rural Girardota", "Urbana Girardota"],
  Itagüí: [
    "Calatrava",
    "El Rosario",
    "Rural",
    "San Pio",
    "Santa Maria",
    "San Francisco",
    "Z. Centro",
  ],
  "La Estrella": ["Rural La Estrella", "Urbana La Estrella"],
  Sabaneta: ["Rural Sabaneta", "Urbana Sabaneta"],
};
